CATL-1579: Single Case Role
compucorp/uk.co.compucorp.civicase pull request #568
Opened 2020-09-02 11:20 UTC by deb1990

## Overview
_A brief description of the pull request. Try to keep it non-technical._

## Before
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## After
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## Technical Details
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

### Core overrides
_If the PR overrides/patches a core file, then please explain here, for each file:_

1. _Which file it is_
2. _The reason why it was overridden/patched_
3. _What the override/patch consists of_

## Comments
_Anything else you would like the reviewer to note_

2020-09-03 09:37 UTC, tunbola requested changes

2020-09-03 09:37 UTC, tunbola commented on ang/civicase/case/details/people-tab/directives/case-details-people-tab.directive.js
> +    var REASSINGMENT_DATE_MESSAGE = ts('Reassignment date cannot be before start date of the relationship.');
Typo. Should be `REASSIGNMENT` instead of `REASSINGMENT`

2020-09-03 09:41 UTC, tunbola approved these changes

2020-09-08 11:45 UTC, tunbola approved these changes

2020-09-09 14:15 UTC, reneolivo approved these changes

2020-09-09 15:41 UTC, merged