Rse 1096 awards instance fe work
compucorp/uk.co.compucorp.civicase pull request #571
Opened 2020-09-04 09:51 UTC by deb1990

## Overview
_A brief description of the pull request. Try to keep it non-technical._

## Before
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## After
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## Technical Details
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

### Core overrides
_If the PR overrides/patches a core file, then please explain here, for each file:_

1. _Which file it is_
2. _The reason why it was overridden/patched_
3. _What the override/patch consists of_

## Comments
_Anything else you would like the reviewer to note_

2020-09-08 21:53 UTC, reneolivo requested changes

2020-09-08 21:53 UTC, reneolivo commented on ang/civicase-base/providers/case-type-category.provider.js
> +      var sentCaseTypeCategory = _.find(caseCategoryInstanceMapping, function (instanceMap) {
`caseTypeCategory` is enough to understand the role of this value.

2020-09-08 21:53 UTC, reneolivo commented on ang/civicase-base/providers/case-type-category.provider.js
> +      var sentInstanceID = _.find(caseCategoryInstanceType, function (instance) {
`instanceId` is enough too.

2020-09-08 21:53 UTC, reneolivo commented on ang/civicase-base/providers/case-type-category.provider.js
> +     * @returns {Array} list of case type categories matching the sent instance
can we use `object[]` instead of `Array`? `Array` can contain any type of data, but `object[]` means that it's an array of objects.

2020-09-09 05:37 UTC, deb1990 commented on .github/workflows/linters.yml
> +      run: git diff --diff-filter=d  origin/${GITHUB_BASE_REF} --name-only -- '*.php' | xargs -r ./bin/phpcs.phar --standard=phpcs-ruleset.xml
Added to documentation. This is just a linter fix.

2020-09-09 10:55 UTC, reneolivo approved these changes

2020-09-09 11:16 UTC, merged