CPS-417: Fix Bug With Recent Communication Block
compucorp/uk.co.compucorp.civicase pull request #669
Opened 2020-12-28 07:31 UTC by shahrukh-compucorp

## Overview
This pr fixes the issue with email activity in recent communication block on case summary page. When user clicked on an email activity in recent communication an error was shown to the user.

## Before
Previously when user clicked on an email activity in recent communication a request was sent to civicrm to edit the activity but civicrm does not allow editing of an email activity so an error was thrown as shown below.
![image-20201208-163955](https://user-images.githubusercontent.com/68388745/103196301-c09b4f00-4905-11eb-8818-380c251dc635.png)

## After
This pr changes the request from edit to view for email activities in recent communication so now when user clicks on an email activity a view of the activity is opened up in a popup.
![Peek 2020-12-28 12-27](https://user-images.githubusercontent.com/68388745/103197796-8d0df400-4908-11eb-8803-fec243f3442c.gif)

## Technical Details
`ang/civicase/activity/factories/view-in-popup.factory.js` file is responsible for providing services for either view or update of an activity. This pr introduces a check in `viewInPopup` function which checks if the type of an activity is email then fetch view service otherwise update service.

2020-12-28 08:00 UTC, deb1990 requested changes

2020-12-28 08:00 UTC, deb1990 commented on ang/civicase/activity/factories/view-in-popup.factory.js
> +        action: activity.type.toLowerCase() === 'email' ? 'view' : 'update'
Also we need to add unit tests for the file. Please try, else I can help you.

2021-01-05 12:31 UTC, reneolivo approved these changes

2021-01-06 10:45 UTC, deb1990 approved these changes

2021-01-06 10:45 UTC, merged