ACU-493: CRM Date Filter
compucorp/uk.co.compucorp.civicase pull request #695
Opened 2021-02-08 21:03 UTC by reneolivo

## Overview
This PR adds a new AngularJS filter that formats date strings coming from the API into human readable formats as defined by the CiviCRM configuration.

This PR is related to https://github.com/compucorp/uk.co.compucorp.civiawards/pull/184

## Before & After

Please look at the "Due Date" column in
https://github.com/compucorp/uk.co.compucorp.civiawards/pull/184

## Technical Details

* A new gulp test:watch task was added. This gulp task makes working with tests easier, specially when doing TDD.
* A new `crm-date.filter.js` filter was created. This one is different from `format-date.filter.js` because the one introduced by us formats the date automatically to what CiviCRM dictates using jQuery UI date formats, and `format-date.filter.js` needs a format passed to it using MomentJS format.

2021-02-09 06:05 UTC, deb1990 requested changes

2021-02-09 06:05 UTC, deb1990 commented on ang/civicase-base/filters/crm-date.filter.js
> +  module.filter('crmDate', crmDate);
As this is defined in Civicase, we should name if `civicaseCrmDate` or just `civicaseDate`.

2021-02-11 06:58 UTC, swastikpareek commented
@reneolivo : 
* Please fix the title to add more info to it. Something like `ACU-493: Add crmDate filter and style no result behavior for case tabs`.
* According to the PR guidelines - https://compucorp.atlassian.net/wiki/spaces/SD/pages/1520304185/Pull+Requests+guidelines, we mentioned what is being changed and how, and doesn't mention why this was needed. Should we add more details to the overview section?
* Also `Empty tabs` section doesn't have a before screenshot. Should we add it?

2021-02-15 12:09 UTC, deb1990 approved these changes

2021-02-15 23:57 UTC, merged