CATL-2105: Change Client Token To Recipient
compucorp/uk.co.compucorp.civicase pull request #707
Opened 2021-02-18 13:28 UTC by shahrukh-compucorp

## Overview
This pr renames client tokens to recipient and change the case client role order in the token tree.

## Before
Client token were available twice
![before](https://user-images.githubusercontent.com/68388745/108363585-eb739680-7216-11eb-9f07-ee65f177f9b4.gif)

## After
The client tokens has been reamed to recipient and case client role token has been moved to second spot in the token tree.
![after](https://user-images.githubusercontent.com/68388745/108363689-0c3bec00-7217-11eb-919a-6975f0681ee4.gif)

## Technical Details
The token tree hook in `CRM/Civicase/Hook/BuildForm/TokenTree.php` has been modified to achieve above defined results.

2021-02-19 07:23 UTC, jamienovick commented
@shahrukh-compucorp please check the latest version of the spec. I think this field set should be "Email Recipient" but should be hidden on the PDF version I believe was the final decision in the end? @shitijg @sohaib-compucorp

2021-02-19 08:31 UTC, shahrukh-compucorp commented
@jamienovick yes I have changed as per the new spec will update the pr description as well

2021-02-19 08:34 UTC, jamienovick commented
Many thanks. Apologies this is moving around a lot at the last minute...

2021-02-19 13:24 UTC, tunbola requested changes

2021-02-19 13:24 UTC, tunbola commented on CRM/Civicase/Hook/BuildForm/TokenTree.php
> +    }
We can simplify this a little bit

```php

    $tokenTexts = [
      0 => self::CASE_TOKEN_TEXT,
      2 => self::RECIPIENT_TOKEN_TEXT,
      3 => self::CURRENT_USER_TOKEN_TEXT,
    ];


    if (in_array($caseClientRole, $this->caseRolesTokenNames)) {
      $this->caseRolesTokenNames = array_diff(
        $this->caseRolesTokenNames,
        [$caseClientRole]
      );
      $tokenTexts[1] = $caseClientRole;
    }


```

2021-02-22 13:03 UTC, lisandro-compucorp submitted a review, later dismissed
:+1

2021-02-23 05:38 UTC, deb1990 approved these changes

2021-02-23 06:09 UTC, merged