CPS-519: Other Relationship Pagination
compucorp/uk.co.compucorp.civicase pull request #748
Opened 2021-03-24 08:51 UTC by deb1990

## Overview
_A brief description of the pull request. Try to keep it non-technical._

## Before
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## After
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## Technical Details
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

### Core overrides
_If the PR overrides/patches a core file, then please explain here, for each file:_

1. _Which file it is_
2. _The reason why it was overridden/patched_
3. _What the override/patch consists of_

## Comments
_Anything else you would like the reviewer to note_

2021-03-26 12:32 UTC, reneolivo requested changes

2021-03-26 12:32 UTC, reneolivo commented on .htmlhintrc
> +}
it would be good to mention this on the description.

Also, where did we get these values from? (in the description as well please :) )

2021-03-26 12:32 UTC, reneolivo commented on ang/civicase/case/details/people-tab/directives/case-roles-tab.directive.html
> +    <civicase-paging
nice!!!

2021-03-26 12:32 UTC, reneolivo commented on ang/civicase/case/details/people-tab/directives/case-roles-tab.directive.html
> +    </civicase-relationship-letter-filter>
why not use `ng-model` and `ng-change` ? we should try to follow the standard.
https://stackoverflow.com/questions/44875989/angularjs-custom-form-component-directive-using-ng-model

2021-03-30 12:05 UTC, reneolivo approved these changes

2021-03-30 15:09 UTC, tunbola submitted a review, later dismissed

2021-04-05 07:16 UTC, lisandro-compucorp approved these changes
As requested, I reviewed the last commit, and it is looking good 👍

2021-04-12 12:02 UTC, merged