MAE-823: Fix bulk mail
compucorp/uk.co.compucorp.civicase pull request #868
Opened 2022-09-02 14:17 UTC by olayiwola-compucorp

## Overview

## Before

## After

## Technical Details

2022-09-05 13:14 UTC, omarabuhussein requested changes
I left two minor notes, but I will also ask to do this if you haven't already:

- test the bulk email sending on our current Civi version but add `define('CIVICRM_DEBUG_LOG_QUERY', 1);` to the civicrm.settings.php file and make a note of what gets "Inserted" or "Updated" into the database.
- do the same with the Civi 5.51.3 with this fix you have here

then compare both to make sure the behavior before and after (aside from the double email) still the same .

2022-09-05 13:14 UTC, omarabuhussein commented on CRM/Civicase/Hook/ValidateForm/SendBulkEmail.php
> +      // and to field.
"and the 'To' field."

2022-09-05 13:14 UTC, omarabuhussein commented on CRM/Civicase/Hook/ValidateForm/SendBulkEmail.php
> +      "$messageSentCount messages were sent successfully",
you should keep the `.` .. also : "message(s)" instead of "messages"

2022-09-06 06:50 UTC, olayiwola-compucorp commented
> I left two minor notes, but I will also ask to do this if you haven't already:
> 
> * test the bulk email sending on our current Civi version but add `define('CIVICRM_DEBUG_LOG_QUERY', 1);` to the civicrm.settings.php file and make a note of what gets "Inserted" or "Updated" into the database.
> * do the same with the Civi 5.51.3 with this fix you have here
> 
> then compare both to make sure the behavior before and after (aside from the double email) still the same .

INSERTs using CiviCRM 5.51.3
```
$Query = INSERT INTO `civicrm_activity` (`activity_type_id` , `subject` , `activity_date_time` , `details` , `status_id` , `priority_id` ) VALUES ( 3 , 'Medi' ,  20220906064641 , '<p>Hello</p>' ,  2 ,  2 ) 
 $Query = INSERT INTO `civicrm_activity_contact` (`activity_id` , `contact_id` , `record_type_id` ) VALUES ( 431 ,  2 ,  2 ) 
 $Query = INSERT INTO `civicrm_log` (`entity_table` , `entity_id` , `data` , `modified_id` , `modified_date` ) VALUES ('civicrm_activity' ,  431 , 'Activity created for source=2' ,  2 ,  20220906064641 ) 
 $Query = INSERT INTO `civicrm_case_activity` (`case_id` , `activity_id` ) VALUES ( 1 ,  431 ) 
 $Query = INSERT INTO `civicrm_mailing` (`domain_id` , `header_id` , `footer_id` , `name` , `from_name` , `from_email` , `replyto_email` , `subject` , `body_html` , `url_tracking` , `forward_replies` , `auto_responder` , `open_tracking` , `is_completed` , `override_verp` , `created_id` , `created_date` , `scheduled_id` , `scheduled_date` , `is_archived` , `visibility` ) VALUES ( 1 ,  NULL ,  NULL , '[case #4d4d8bf] Medi' , 'Organisation' , '1054_31@example.com' , '1054_31@example.com' , '[case #4d4d8bf] Medi' , 'MIME-Version: 1.0\nFrom: &quot;Ms compucorp admin&quot; &lt;compucorp@gmail.com&gt;\nTo: 1AnonymousAnonymous1 &lt;1_anonymous_1@example.com&gt;\nSubject: [case #4d4d8bf] Medi\nReturn-Path: compucorp@gmail.com\nReply-To: &quot;Ms compucorp admin&quot; &lt;compucorp@gmail.com&gt;\nDate: Tue, 06 Sep 2022 06:46:41 +0100\nContent-Type: multipart/alternative;\n boundary=&quot;=_494dface92441f5823840f6e2c32a57e&quot;\n\n--=_494dface92441f5823840f6e2c32a57e\nContent-Transfer-Encoding: 8bit\nContent-Type: text/plain; charset=utf-8\n\nHello\n--=_494dface92441f5823840f6e2c32a57e\nContent-Transfer-Encoding: 8bit\nContent-Type: text/html; charset=utf-8\n\n<p>Hello</p>\n--=_494dface92441f5823840f6e2c32a57e--\n' ,  1 ,  0 ,  0 ,  1 ,  1 ,  1 ,  2 ,  20220906064641 ,  2 ,  20220906064641 ,  1 , 'Public Pages' ) 
 $Query = INSERT INTO `civicrm_mailing_job` (`mailing_id` , `status` , `is_test` ) VALUES ( 134 , 'Complete' ,  0 ) 
 $Query = INSERT INTO `civicrm_mailing_job` (`mailing_id` , `scheduled_date` , `start_date` , `end_date` , `status` , `is_test` ) VALUES ( 134 ,  20220906064641 ,  20220906064641 ,  20220906064641 , 'Complete' ,  0 ) 
 $Query = INSERT INTO `civicrm_mailing_job` (`mailing_id` , `scheduled_date` , `start_date` , `end_date` , `status` , `is_test` , `job_type` , `parent_id` ) VALUES ( 134 ,  20220906064641 ,  20220906064641 ,  20220906064641 , 'Complete' ,  0 , 'child' ,  363 ) 
 $Query = INSERT INTO `civicrm_mailing_spool` (`job_id` , `recipient_email` , `headers` , `body` , `added_at` ) VALUES ( 364 , '1_anonymous_1@example.com' , 'MIME-Version: 1.0\nFrom: \"Ms compucorp admin\" <compucorp@gmail.com>\nTo: 1AnonymousAnonymous1 <1_anonymous_1@example.com>\nSubject: [case #4d4d8bf] Medi\nReturn-Path: compucorp@gmail.com\nReply-To: \"Ms compucorp admin\" <compucorp@gmail.com>\nDate: Tue, 06 Sep 2022 06:46:41 +0100\nContent-Type: multipart/alternative;\n boundary=\"=_494dface92441f5823840f6e2c32a57e\"' , '--=_494dface92441f5823840f6e2c32a57e\nContent-Transfer-Encoding: 8bit\nContent-Type: text/plain; charset=utf-8\n\nHello\n--=_494dface92441f5823840f6e2c32a57e\nContent-Transfer-Encoding: 8bit\nContent-Type: text/html; charset=utf-8\n\n<p>Hello</p>\n--=_494dface92441f5823840f6e2c32a57e--\n' ,  20220906064641 ) 
 $Query = INSERT INTO `civicrm_activity_contact` (`activity_id` , `contact_id` , `record_type_id` ) VALUES ( 431 ,  1 ,  3 ) 
 $Query = INSERT INTO `civicrm_activity` (`activity_type_id` , `subject` , `activity_date_time` , `details` , `status_id` , `priority_id` ) VALUES ( 3 , 'Medi' ,  20220906064641 , '<p>Hello</p>' ,  2 ,  2 ) 
 $Query = INSERT INTO `civicrm_activity_contact` (`activity_id` , `contact_id` , `record_type_id` ) VALUES ( 432 ,  2 ,  2 ) 
 $Query = INSERT INTO `civicrm_log` (`entity_table` , `entity_id` , `data` , `modified_id` , `modified_date` ) VALUES ('civicrm_activity' ,  432 , 'Activity created for source=2' ,  2 ,  20220906064641 ) 
 $Query = INSERT INTO `civicrm_case_activity` (`case_id` , `activity_id` ) VALUES ( 2 ,  432 ) 
 $Query = INSERT INTO `civicrm_mailing` (`domain_id` , `header_id` , `footer_id` , `name` , `from_name` , `from_email` , `replyto_email` , `subject` , `body_html` , `url_tracking` , `forward_replies` , `auto_responder` , `open_tracking` , `is_completed` , `override_verp` , `created_id` , `created_date` , `scheduled_id` , `scheduled_date` , `is_archived` , `visibility` ) VALUES ( 1 ,  NULL ,  NULL , '[case #5c97fa4] Medi' , 'Organisation' , '1054_31@example.com' , '1054_31@example.com' , '[case #5c97fa4] Medi' , 'MIME-Version: 1.0\nFrom: &quot;Ms compucorp admin&quot; &lt;compucorp@gmail.com&gt;\nTo: compucorp admin &lt;compucorp@gmail.com&gt;\nSubject: [case #5c97fa4] Medi\nReturn-Path: compucorp@gmail.com\nReply-To: &quot;Ms compucorp admin&quot; &lt;compucorp@gmail.com&gt;\nDate: Tue, 06 Sep 2022 06:46:41 +0100\nContent-Type: multipart/alternative;\n boundary=&quot;=_c3018afde51a6a3f3977f54dcbdc7e56&quot;\n\n--=_c3018afde51a6a3f3977f54dcbdc7e56\nContent-Transfer-Encoding: 8bit\nContent-Type: text/plain; charset=utf-8\n\nHello\n--=_c3018afde51a6a3f3977f54dcbdc7e56\nContent-Transfer-Encoding: 8bit\nContent-Type: text/html; charset=utf-8\n\n<p>Hello</p>\n--=_c3018afde51a6a3f3977f54dcbdc7e56--\n' ,  1 ,  0 ,  0 ,  1 ,  1 ,  1 ,  2 ,  20220906064641 ,  2 ,  20220906064641 ,  1 , 'Public Pages' ) 
 $Query = INSERT INTO `civicrm_mailing_job` (`mailing_id` , `status` , `is_test` ) VALUES ( 135 , 'Complete' ,  0 ) 
 $Query = INSERT INTO `civicrm_mailing_job` (`mailing_id` , `scheduled_date` , `start_date` , `end_date` , `status` , `is_test` ) VALUES ( 135 ,  20220906064641 ,  20220906064641 ,  20220906064641 , 'Complete' ,  0 ) 
$Query = INSERT INTO `civicrm_mailing_job` (`mailing_id` , `scheduled_date` , `start_date` , `end_date` , `status` , `is_test` , `job_type` , `parent_id` ) VALUES ( 135 ,  20220906064641 ,  20220906064641 ,  20220906064641 , 'Complete' ,  0 , 'child' ,  366 ) 
$Query = INSERT INTO `civicrm_mailing_spool` (`job_id` , `recipient_email` , `headers` , `body` , `added_at` ) VALUES ( 367 , 'compucorp@gmail.com' , 'MIME-Version: 1.0\nFrom: \"Ms compucorp admin\" <compucorp@gmail.com>\nTo: compucorp admin <compucorp@gmail.com>\nSubject: [case #5c97fa4] Medi\nReturn-Path: compucorp@gmail.com\nReply-To: \"Ms compucorp admin\" <compucorp@gmail.com>\nDate: Tue, 06 Sep 2022 06:46:41 +0100\nContent-Type: multipart/alternative;\n boundary=\"=_c3018afde51a6a3f3977f54dcbdc7e56\"' , '--=_c3018afde51a6a3f3977f54dcbdc7e56\nContent-Transfer-Encoding: 8bit\nContent-Type: text/plain; charset=utf-8\n\nHello\n--=_c3018afde51a6a3f3977f54dcbdc7e56\nContent-Transfer-Encoding: 8bit\nContent-Type: text/html; charset=utf-8\n\n<p>Hello</p>\n--=_c3018afde51a6a3f3977f54dcbdc7e56--\n' ,  20220906064641 ) 
$Query = INSERT INTO `civicrm_activity_contact` (`activity_id` , `contact_id` , `record_type_id` ) VALUES ( 432 ,  2 ,  3 ) 

```

INSERTs using CiviCRM 5.39.1
```
$Query = INSERT INTO `civicrm_activity` (`activity_type_id` , `subject` , `activity_date_time` , `details` , `status_id` , `priority_id` ) VALUES ( 3 , 'Medi' ,  20220906064407 , '<p>Hello</p>' ,  2 ,  2 ) 
 $Query = INSERT INTO `civicrm_activity_contact` (`activity_id` , `contact_id` , `record_type_id` ) VALUES ( 418 ,  2 ,  2 ) 
 $Query = INSERT INTO `civicrm_log` (`entity_table` , `entity_id` , `data` , `modified_id` ,  [...]

2022-09-06 08:05 UTC, omarabuhussein approved these changes

2022-09-06 08:57 UTC, merged